### ISSUE TITLE
would you please release the model which is trained on 120 pair images?

### ISSUE THREAD

**Issue by qweasdzxc110** [yiranran/APDrawingGAN#11]
when i test the current model(trained on 70 images), there are some lines around eyes and mouth in model' outputs. But i test in your online service, it's perfect!

**Comment by rjadr** [comment]
I assume the 1.21GB model under [this link](https://github.com/yiranran/APDrawingGAN/issues/8#issuecomment-535162837) is the 120 pair one.

**Comment by yiranran** [comment]
Sorry we wouldn't release the 120 pair model. 
However, you could try training using 120 pairs from our dataset. Since we already provided the data and training code, it won't require much effort.
