### ISSUE TITLE
预训练模型效果不如online demo

### ISSUE THREAD

**Issue by OptimusPrimeCao** [yiranran/APDrawingGAN#12]
你好，我用同一张测试图，使用预训练下载的模型和网上的demo接口效果差距挺大的，能放一下网上demo对应的模型吗

**Comment by yiranran** [comment]
您好因为demo里用了120对图训练，提供的模型只用了70对图训（paper里的版本）。demo里还加了一些优化。所以导致有些区别。

**Comment by OptimusPrimeCao** [comment]
@yiranran 可以下载demo对应的模型吗
