### ISSUE TITLE
test.py: error: the following arguments are required: --dataroot 请问下我运行后出现这个问题。

### ISSUE THREAD

**Issue by Wang-zhechao** [yiranran/APDrawingGAN#14]
usage: test.py [-h] --dataroot DATAROOT [--batch_size BATCH_SIZE]
               [--loadSize LOADSIZE] [--fineSize FINESIZE]
               [--input_nc INPUT_NC] [--output_nc OUTPUT_NC] [--ngf NGF]
               [--ndf NDF] [--netD NETD] [--netG NETG] [--nnG NNG]
               [--n_layers_D N_LAYERS_D] [--gpu_ids GPU_IDS] [--name NAME]
               [--dataset_mode DATASET_MODE] [--model MODEL] [--use_local]
               [--comb_op COMB_OP] [--lm_dir LM_DIR] [--bg_dir BG_DIR]
               [--soft_border SOFT_BORDER] [--EYE_H EYE_H] [--EYE_W EYE_W]
               [--NOSE_H NOSE_H] [--NOSE_W NOSE_W] [--MOUTH_H MOUTH_H]
               [--MOUTH_W MOUTH_W] [--which_direction WHICH_DIRECTION]
               [--num_threads NUM_THREADS] [--checkpoints_dir CHECKPOINTS_DIR]
               [--auxiliary_root AUXILIARY_ROOT] [--norm NORM]
               [--serial_batches] [--display_winsize DISPLAY_WINSIZE]
               [--display_id DISPLAY_ID] [--display_server DISPLAY_SERVER]
               [--display_env DISPLAY_ENV] [--display_port DISPLAY_PORT]
               [--no_dropout] [--max_dataset_size MAX_DATASET_SIZE]
               [--resize_or_crop RESIZE_OR_CROP] [--no_flip]
               [--init_type INIT_TYPE] [--init_gain INIT_GAIN] [--verbose]
               [--suffix SUFFIX] [--ntest NTEST] [--results_dir RESULTS_DIR]
               [--aspect_ratio ASPECT_RATIO] [--phase PHASE]
               [--which_epoch WHICH_EPOCH] [--how_many HOW_MANY] [--save2]
test.py: error: the following arguments are required: --dataroot

**Comment by yiranran** [comment]
You can use this command (in readme)
python test.py --dataroot dataset/data/test_single --name formal_author --model test --dataset_mode single --norm batch --use_local --which_epoch 300
