### ISSUE TITLE
Can I use the local generators as output to get differnet parts of portrait ? 

### ISSUE THREAD

**Issue by dreamer121121** [yiranran/APDrawingGAN#21]
If i not only need the total portrait but also need the local parts of a portrait, such as eyes, ears, noses, and so on ,can i use the local generator as output to get the different parts ?

**Comment by yiranran** [comment]
Yes, but currently the outputs from local generators are less delicate, since we mainly supervise the fused result from fusion network. You may try supervising the outputs from local generators directly.
