### ISSUE TITLE
可以在windows上运行吗？

### ISSUE THREAD

**Issue by ghost** [yiranran/APDrawingGAN#5]
必须要搭载linux or mac os的设备吗

**Comment by yiranran** [comment]
Sorry I have not tested on windows.

**Comment by WellenWoo** [comment]
经过测试，可以在Windows上运行，我的环境是win10 + py36+ torch1.1

**Comment by ChauvinisticJonatha** [comment]
> 经过测试，可以在Windows上运行，我的环境是win10 + py36+ torch1.1

TypeError: only integer tensors of a single element can be converted to an index  ,你报这个错误了吗

**Comment by yiranran** [comment]
> > 经过测试，可以在Windows上运行，我的环境是win10 + py36+ torch1.1
> 
> TypeError: only integer tensors of a single element can be converted to an index ,你报这个错误了吗

Please refer to this [issue](https://github.com/yiranran/APDrawingGAN/issues/10)
