### ISSUE TITLE
Dataset and Pre-train model

### ISSUE THREAD

**Issue by hosytuyen** [yiranran/APDrawingGAN#8]
Hi, The APDarwingGAN is great
Currently I'm using this for my study. As you mention in paper you have published APDrawingDB dataset and pre-train model but I can't get into the link. Could you please fix the link or share them in another way?
Thank you so much.

**Comment by yiranran** [comment]
The server that hosts the data is having some temporary network issues 
Here is an alternative baiduyun link: https://pan.baidu.com/s/1dSXOYa8te3vbKJFifdc5Jg
extract code is: jzk0
(You could try pandownload if downloading speed is slow)
