### ISSUE TITLE
Can not use the online version in https://face.lol

### ISSUE THREAD

**Issue by qwzlh** [yiranran/APDrawingGAN#9]
Hello,  
I think this is a great work, but I find that I can not use the online version of your work in  https://face.lol. Is there any problem with the web server?

**Comment by qwzlh** [comment]
The google chrome always tells me that the serve is busy.

**Comment by Ricelll** [comment]
Me either.The serve is busy.

**Comment by yiranran** [comment]
Sorry, the server that hosts demo was going on some problems, it will be fixed in a few days.

**Comment by yiranran** [comment]
The demo website has been recovered.

**Comment by ava-YangL** [comment]
Me too, The server is busy now~   T.T

**Comment by yiranran** [comment]
The demo is working now

**Comment by tfwang08** [comment]
The server is busy now again.

**Comment by chengweiv5** [comment]
still busy.

**Comment by jfooyh** [comment]
Server is still busy. Able to check why please?

**Comment by apdrawing** [comment]
We update the demo website. The new page is https://apdrawing.github.io/
And the current version supports multi-style generation.

**Comment by yiranran** [comment]
We update the demo website. The new page is https://apdrawing.github.io/
And the current version supports multi-style generation.
